name: build

on:
  push:
    branches: v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup go environment
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
      - name: run unit tests
        run: make test
      - name: run acceptance tests
        run: |
          export LOCAL_REGISTRY_HOSTNAME="$(hostname -I | awk '{print $1}')"
          make acceptance
      - name: upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: oras-coverage-report-${{ github.sha }}
          path: .cover/
        if: always()
