name: build-pr

on:
  pull_request:
    branches:
      - v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.18.9'
      - name: run unit tests
        run: make test
      - name: run acceptance tests
        run: |
          export LOCAL_REGISTRY_HOSTNAME="$(hostname -I | awk '{print $1}')"
          make acceptance
      - name: upload coverage report
        uses: actions/upload-artifact@master
        with:
          name: oras-coverage-report-${{ github.sha }}
          path: .cover/
        if: always()
